//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSpa
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_HOADON
    {
        public int MAHD { get; set; }
        public int MASP { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<double> DONGIA { get; set; }
        public string NOIDUNG { get; set; }
        public string CHUTHICH { get; set; }
    
        public virtual HOADONBAN HOADONBAN { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
