//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSpa
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_HOADON_DICHVU_DIEUTRI
    {
        public int MADHDV { get; set; }
        public int MADV { get; set; }
        public int LAN { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<double> DONGIA { get; set; }
        public string CHUTHICH { get; set; }
        public string LICHSU { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual HOADON_DICHVU HOADON_DICHVU { get; set; }
        public virtual LAN_DIEUTRI LAN_DIEUTRI { get; set; }
    }
}
