//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSpa
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICHVU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DICHVU()
        {
            this.CHITIET_HOADON_DICHVU_DIEUTRI = new HashSet<CHITIET_HOADON_DICHVU_DIEUTRI>();
            this.CHITIET_KHUYENMAI_DICHVU = new HashSet<CHITIET_KHUYENMAI_DICHVU>();
            this.HOADON_DICHVU = new HashSet<HOADON_DICHVU>();
        }
    
        public int MADV { get; set; }
        public string DV_TEN { get; set; }
        public Nullable<bool> DV_TRANGTHAI { get; set; }
        public Nullable<int> DV_CHA { get; set; }
        public string HINHANH1 { get; set; }
        public string HINHANH2 { get; set; }
        public string HINHANH3 { get; set; }
        public string HINHANH4 { get; set; }
        public string HINHANH5 { get; set; }
        public Nullable<double> DV_GIA { get; set; }
        public string DV_THONGTIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HOADON_DICHVU_DIEUTRI> CHITIET_HOADON_DICHVU_DIEUTRI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_KHUYENMAI_DICHVU> CHITIET_KHUYENMAI_DICHVU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON_DICHVU> HOADON_DICHVU { get; set; }
    }
}
