//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSpa
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONBAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADONBAN()
        {
            this.CHITIET_HOADON = new HashSet<CHITIET_HOADON>();
        }
    
        public int MAHD { get; set; }
        public int MAND { get; set; }
        public int MATT { get; set; }
        public int MATTHD { get; set; }
        public string TENKHACH { get; set; }
        public Nullable<int> MAKH { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
        public Nullable<bool> HD_TRANGTHAI { get; set; }
        public Nullable<int> MANV { get; set; }
        public string TENNV { get; set; }
        public string LICHSU { get; set; }
        public string CHUTHICH { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HOADON> CHITIET_HOADON { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual THANHTOAN THANHTOAN { get; set; }
        public virtual TRANGTHAIHOADON TRANGTHAIHOADON { get; set; }
    }
}
