//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSpa
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON_DICHVU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON_DICHVU()
        {
            this.CHITIET_HOADON_DICHVU_DIEUTRI = new HashSet<CHITIET_HOADON_DICHVU_DIEUTRI>();
        }
    
        public int MADHDV { get; set; }
        public int MADV { get; set; }
        public int MAND { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
        public string LICHSU { get; set; }
        public Nullable<bool> HDDV_TRANGTHAI { get; set; }
        public string HINHANH1 { get; set; }
        public string HINHANH2 { get; set; }
        public string HINHANH3 { get; set; }
        public string HINHANH4 { get; set; }
        public string HINHANH5 { get; set; }
        public string HINHANH6 { get; set; }
        public string HINHANH7 { get; set; }
        public string HINHANH8 { get; set; }
        public string HINHANH9 { get; set; }
        public string HINHANH10 { get; set; }
        public string HINHANH11 { get; set; }
        public string HINHANH12 { get; set; }
        public string HINHANH13 { get; set; }
        public string HINHANH14 { get; set; }
        public string HINHANH15 { get; set; }
        public string HINHANH16 { get; set; }
        public string HINHANH17 { get; set; }
        public string HINHANH18 { get; set; }
        public string HINHANH19 { get; set; }
        public string HINHANH20 { get; set; }
        public string VIDEO1 { get; set; }
        public string VIDEO2 { get; set; }
        public string VIDEO3 { get; set; }
        public string VIDEO4 { get; set; }
        public string VIDEO5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HOADON_DICHVU_DIEUTRI> CHITIET_HOADON_DICHVU_DIEUTRI { get; set; }
        public virtual DICHVU DICHVU { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
