//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSpa
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUYENMAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHUYENMAI()
        {
            this.CHITIET_KHUYENMAI_DICHVU = new HashSet<CHITIET_KHUYENMAI_DICHVU>();
            this.CHITIET_KHUYENMAI_SANPHAM = new HashSet<CHITIET_KHUYENMAI_SANPHAM>();
        }
    
        public int MAKM { get; set; }
        public string KM_TEN { get; set; }
        public Nullable<System.DateTime> TUNGAY { get; set; }
        public Nullable<System.DateTime> DENNGAY { get; set; }
        public string NOIDUNG { get; set; }
        public string CHUTHICH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_KHUYENMAI_DICHVU> CHITIET_KHUYENMAI_DICHVU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_KHUYENMAI_SANPHAM> CHITIET_KHUYENMAI_SANPHAM { get; set; }
    }
}
