//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSpa
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAN_DIEUTRI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LAN_DIEUTRI()
        {
            this.CHITIET_HOADON_DICHVU_DIEUTRI = new HashSet<CHITIET_HOADON_DICHVU_DIEUTRI>();
        }
    
        public int LAN { get; set; }
        public string CHUTHICH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HOADON_DICHVU_DIEUTRI> CHITIET_HOADON_DICHVU_DIEUTRI { get; set; }
    }
}
