//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSpa
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAISANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAISANPHAM()
        {
            this.SANPHAMs = new HashSet<SANPHAM>();
            this.TRANGTHAI_SANPHAM = new HashSet<TRANGTHAI_SANPHAM>();
        }
    
        public int MALSP { get; set; }
        public string LSP_TEN { get; set; }
        public string LSP_HINH1 { get; set; }
        public string LSP_HINH2 { get; set; }
        public string LSP_HINH3 { get; set; }
        public string LSP_HINH4 { get; set; }
        public string LSP_HINH5 { get; set; }
        public Nullable<int> LSP_CHA { get; set; }
        public Nullable<bool> LSP_TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANGTHAI_SANPHAM> TRANGTHAI_SANPHAM { get; set; }
    }
}
