//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSpa
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUOIDUNG()
        {
            this.HOADON_DICHVU = new HashSet<HOADON_DICHVU>();
            this.HOADONBANs = new HashSet<HOADONBAN>();
            this.PHIEUNHAPs = new HashSet<PHIEUNHAP>();
        }
    
        public int MAND { get; set; }
        public int MAPHUONG { get; set; }
        public int MAQUYEN { get; set; }
        public string ND_CODE { get; set; }
        public string ND_CMND1 { get; set; }
        public string ND_CMND2 { get; set; }
        public string ND_CMND3 { get; set; }
        public string ND_CMND4 { get; set; }
        public string ND_CMND5 { get; set; }
        public string ND_SDT1 { get; set; }
        public string ND_SDT2 { get; set; }
        public string ND_SDT3 { get; set; }
        public string ND_SDT4 { get; set; }
        public string ND_SDT5 { get; set; }
        public string ND_STK { get; set; }
        public string ND_HINHANH { get; set; }
        public Nullable<bool> ND_GIOITINH { get; set; }
        public string ND_DIACHI1 { get; set; }
        public string ND_DIACHI2 { get; set; }
        public string ND_TEN { get; set; }
        public Nullable<bool> KICHHOAT { get; set; }
        public Nullable<bool> VIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON_DICHVU> HOADON_DICHVU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONBAN> HOADONBANs { get; set; }
        public virtual PHUONG PHUONG { get; set; }
        public virtual QUYEN QUYEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUNHAP> PHIEUNHAPs { get; set; }
    }
}
