//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSpa
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHACUNGCAP
    {
        public int MANCC { get; set; }
        public int MAPHUONG { get; set; }
        public string NCC_TEN { get; set; }
        public string NCC_DIACHI { get; set; }
        public string NCC_SDT1 { get; set; }
        public string NCC_SDT2 { get; set; }
        public string NCC_STK { get; set; }
        public string NCC_MASOTHUE { get; set; }
        public Nullable<bool> NCC_TRANGTHAI { get; set; }
    
        public virtual PHUONG PHUONG { get; set; }
    }
}
