//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSpa
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNHAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUNHAP()
        {
            this.CHITIET_PHIEUNHAP = new HashSet<CHITIET_PHIEUNHAP>();
        }
    
        public int MAPN { get; set; }
        public int MAND { get; set; }
        public Nullable<System.DateTime> PN_NGAY { get; set; }
        public Nullable<int> PN_TRANGTHAI { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
        public string LICHSU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_PHIEUNHAP> CHITIET_PHIEUNHAP { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
