//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSpa
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUAN_HUYEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUAN_HUYEN()
        {
            this.PHUONGs = new HashSet<PHUONG>();
        }
    
        public int MAQUAN { get; set; }
        public int MATP { get; set; }
        public string QUAN_TEN { get; set; }
        public Nullable<bool> QUAN_TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHUONG> PHUONGs { get; set; }
        public virtual THANHPHO THANHPHO { get; set; }
    }
}
