//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSpa
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIET_HOADON = new HashSet<CHITIET_HOADON>();
            this.CHITIET_KHUYENMAI_SANPHAM = new HashSet<CHITIET_KHUYENMAI_SANPHAM>();
        }
    
        public int MASP { get; set; }
        public int MATTSP { get; set; }
        public int MALSP { get; set; }
        public int MADVT { get; set; }
        public string SP_CODE { get; set; }
        public string SP_TEN { get; set; }
        public string SP_MOTA { get; set; }
        public Nullable<double> SP_GIA { get; set; }
        public Nullable<int> SP_LUOTXEM { get; set; }
        public Nullable<int> SP_LUOTMUA { get; set; }
        public string SP_HINH1 { get; set; }
        public string SP_HINH2 { get; set; }
        public string SP_HINH3 { get; set; }
        public string SP_HINH4 { get; set; }
        public string SP_HINH5 { get; set; }
        public string LICHSU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HOADON> CHITIET_HOADON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_KHUYENMAI_SANPHAM> CHITIET_KHUYENMAI_SANPHAM { get; set; }
        public virtual DVT DVT { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual TRANGTHAI_SANPHAM TRANGTHAI_SANPHAM { get; set; }
    }
}
